export const permissionCodes = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  USERS_VIEW: "USERS_VIEW",
  USERS_CREATE: "USERS_CREATE",
  USERS_UPDATE: "USERS_UPDATE",
  USERS_DELETE: "USERS_DELETE",

  ROLES_VIEW: "ROLES_VIEW",
  ROLES_CREATE: "ROLES_CREATE",
  ROLES_UPDATE: "ROLES_UPDATE",
  ROLES_DELETE: "ROLES_DELETE",

  USER_TYPES_VIEW: "USER_TYPES_VIEW",
  USER_TYPES_CREATE: "USER_TYPES_CREATE",
  USER_TYPES_UPDATE: "USER_TYPES_UPDATE",
  USER_TYPES_DELETE: "USER_TYPES_DELETE",

  SERVICES_VIEW: "SERVICES_VIEW",
  SERVICES_CREATE: "SERVICES_CREATE",
  SERVICES_UPDATE: "SERVICES_UPDATE",
  SERVICES_DELETE: "SERVICES_DELETE",

  BOOKINGS_VIEW: "BOOKINGS_VIEW",
  BOOKINGS_CREATE: "BOOKINGS_CREATE",
  BOOKINGS_UPDATE: "BOOKINGS_UPDATE",
  BOOKINGS_DELETE: "BOOKINGS_DELETE",

  ASSIGNMENTS_VIEW: "ASSIGNMENTS_VIEW",
  ASSIGNMENTS_CREATE: "ASSIGNMENTS_CREATE",
  ASSIGNMENTS_UPDATE: "ASSIGNMENTS_UPDATE",
  ASSIGNMENTS_DELETE: "ASSIGNMENTS_DELETE",

  HERO_VERIFICATION_VIEW: "HERO_VERIFICATION_VIEW",
  HERO_VERIFICATION_UPDATE: "HERO_VERIFICATION_UPDATE",
  HERO_VERIFICATION_VERIFY: "HERO_VERIFICATION_VERIFY",
  HERO_VERIFICATION_REJECT: "HERO_VERIFICATION_REJECT",

  PAYMENTS_VIEW: "PAYMENTS_VIEW",
  PAYMENTS_CREATE: "PAYMENTS_CREATE",
  PAYMENTS_UPDATE: "PAYMENTS_UPDATE",
  PAYMENTS_DELETE: "PAYMENTS_DELETE",

  PERMISSIONS_VIEW: "PERMISSIONS_VIEW",
  PERMISSIONS_ASSIGN: "PERMISSIONS_ASSIGN",
  PERMISSIONS_CREATE: "PERMISSIONS_CREATE",
  PERMISSIONS_UPDATE: "PERMISSIONS_UPDATE",
  PERMISSIONS_DELETE: "PERMISSIONS_DELETE",

  SCREENS_VIEW: "SCREENS_VIEW",
  SCREENS_CREATE: "SCREENS_CREATE",
  SCREENS_UPDATE: "SCREENS_UPDATE",
  SCREENS_DELETE: "SCREENS_DELETE",

  WORKER_STATE_UPDATE: "WORKER_STATE_UPDATE",
  EXPORT: "EXPORT",
} as const;

export type PermissionCode = (typeof permissionCodes)[keyof typeof permissionCodes];
