-- AlterTable
ALTER TABLE `mUsers`
  ADD COLUMN `employmentStatus` ENUM('ACTIVE', 'LEFT') NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN `joinedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `leftAt` DATETIME(3) NULL;