ALTER TABLE `tBookings`
  MODIFY `bookingStatus` ENUM('DRAFT','HOLD','CONFIRMED','PENDING_PAYMENT','PAID','ASSIGNMENT_PENDING','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED','FAILED') NOT NULL DEFAULT 'DRAFT',
  MODIFY `iServiceMasterId` INTEGER NULL,
  ADD COLUMN `requestedServiceName` VARCHAR(191) NULL,
  ADD COLUMN `confirmedAt` DATETIME(3) NULL,
  ADD COLUMN `holdReason` TEXT NULL,
  ADD COLUMN `cancelledAt` DATETIME(3) NULL,
  ADD COLUMN `cancelReason` TEXT NULL;
